### ISSUE TITLE
Readme needs updating?

### ISSUE THREAD

**Issue by Joris-van-der-Wel** [seangarner/node-buffer-peek-stream#1]
The example of the readme looks like this:

``` javascript
peek(readstream, 65536, function (err, data) {
  readstream.pipe(somewhere_else);
});
```

Implementing it like this causes issues for me (I suspect `readstream` keeps draining). However the following seems to work fine:

``` javascript
peek(readstream, 65536, function (err, data, stream) {
  stream.pipe(somewhere_else);
});
```

**Comment by seangarner** [comment]
I've fixed that and published a version bump with no code changes to npm so the docs there are updated too.

Thanks for letting me know @Joris-van-der-Wel
