### ISSUE TITLE
HTTP Response example

### ISSUE THREAD

**Issue by maxcountryman** [seangarner/node-buffer-peek-stream#2]
I'm wondering the proper way to inspect HTTP Response streams?

In particular, I have response streams I would like to inspect within tens of milliseconds, but my attempts so far have failed. What I have looks something like this:

```js
peek(res, 1024, (err, data) => {
  console.log('data', data);
  ...
});
```

However nothing is ever logged to the console even when the timeout is made very long (tens of seconds).

**Comment by seangarner** [comment]
@maxcountryman I assume that it's an [IncomingMessage](https://nodejs.org/dist/latest-v6.x/docs/api/http.html#http_class_http_incomingmessage) stream you're trying to inspect.

I can't say that I've ever tested it with a http stream, so I wrote one in 7ea24c3e57e603f011c28e5f189b2a56ab640b96 and it's working for me.  Perhaps it'll help you.   If not then I'd need more information, ideally a script I can run to reproduce.
